---
title: "p8105_hw2_st3117"
author: "Sha Tao"
date: "October 6, 2018"
output: github_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggridges)
library(patchwork)
library(p8105.datasets)

```

## Problem 1_1 BRFSS Data Cleaning

```{r Problem 1_1}

brfss = 
  brfss_smart2010 %>% 
  janitor::clean_names() %>%
  filter(topic == "Overall Health") %>% 
  separate(locationdesc, into = c("remove2", "county"), sep = 5) %>% 
  select(year, state = locationabbr, county, response, data_value) %>% 
  mutate(response = as.factor(response))

brfss

```

## Problem 1_2 Answering Questions

```{r Problem 1_2}

brfss %>% 
  spread(key = response, value = data_value) %>% 
  janitor::clean_names() %>% 
  filter(year == 2002) %>% 
  group_by(state) %>% 
  summarize(n = n()) %>% 
  filter(n == 7)

brfss %>% 
  filter(year == 2002) %>% 
  group_by(state) %>% 
  summarize(n = n_distinct(county)) %>% 
  filter(n == 7)


```

## Problem 1_3 Spaghetti Plot showing the number of observations in each state from 2002 to 2010s

```{r Problem 1_3}

brfss %>%
  group_by(year, state) %>% 
  summarize(n = n()) %>% 
  ggplot(aes(x = year, y = n, color = state)) +
    geom_line() +
    labs(
      title = "Number of Observations Plot",
      x = "Year",
      y = "Number of Observations"
      ) +
    theme_bw() +
    theme(legend.position = "right")

```

## Problem 1_4 NY State “Excellent” responses

```{r Problem 1_4}

brfss %>%
  filter(state == "NY" & response == "Excellent") %>% 
  filter(year == 2002 | year == 2006 | year == 2010) %>%
  group_by(county) %>%
  summarize(mean_prop = mean(data_value),
            sd_prop = sd(data_value))

```


